services:
  api:
    build: .
    container_name: rag_api
    ports:
      - "8000:8000"
    volumes:
      - ./src/assets:/app/assets
      - ./src/file_metadata.db:/app/file_metadata.db
      - ./src/logs:/app/logs
    env_file:
      - src/.env
    healthcheck:
      disable: true 
    depends_on:
      - redis
      - qdrant
    restart: always

  bot:
    build: .
    container_name: rag_bot
    command: python bot/telegram_bot.py
    volumes:
      - ./src/assets:/app/assets
      - ./src/file_metadata.db:/app/file_metadata.db
      - ./src/logs:/app/logs
    env_file:
      - src/.env
    environment:
      - API_BASE_URL=http://api:8000
    healthcheck:
      disable: true
    depends_on:
      - api
    restart: always

  redis:
    image: redis:alpine
    container_name: rag_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
  redis_data: