from enum import Enum

class ResponseSignal(Enum):

    FILE_TYPE_NOT_SUPPORTED="file type not SUPPORTED"
    FILE_SIZE_NOT_EXCEEDED="file size not EXCEEDED"
    FILE_VALIDATION_SUCC="file validation successfully"
    VECTORDB_CREATED_SUCCESSFULLY="VECTORDB_CREATED_SUCCESSFULLY"
    ADDED_IN_VECTORDB_SUCCESSFULLY="ADDED_IN_VECTORDB_SUCCESSFULLY"
