from enum import Enum

class ResponseSignal(Enum):

    FILE_TYPE_NOT_SUPPORTED="file type not SUPPORTED"
    FILE_SIZE_NOT_EXCEEDED="file size not EXCEEDED"
    FILE_VALIDATION_SUCC="file validation successfully"
    FILE_UPLOAD_FAILED="file upload failed"
    VECTORDB_CREATED_SUCCESSFULLY="VECTORDB_CREATED_SUCCESSFULLY"
    ADDED_IN_VECTORDB_SUCCESSFULLY="ADDED_IN_VECTORDB_SUCCESSFULLY"
    MADE_CHUNKS_SUCCESSFULY="MADE_CHUNKS_SUCCESSFULY"
    ERROR_IN_MAKE_CHUNKS="ERROR_IN_MAKE_CHUNKS"
    ERROR_TO_FOUND_DATABASE_WHILE_ASKING="Vector Database not found. Please process and index your assets first."
    SORRY_TO_FIND_RELEVANT_DATA="I'm sorry, I couldn't find any relevant information in the provided documents to answer your question."
    ERROR_WHILE_PROCESSING_QUESTION="An internal error occurred while processing your question."
    FILE_ALREADY_INDEXED="File is already indexed (duplicate content detected)."
    FILE_VERSION_UPDATED="File version updated successfully."

    PATH_NOT_FOUND="Path {base_path} not found!"
    NO_CHUNKS_GENERATED="No chunks were generated."
    ALL_SKIPPED_DUPLICATE="All files were already indexed (hash duplicates)."
    SEMANTIC_CACHE_CLEARED="Semantic cache cleared successfully."
    CACHE_HIT="hit"
    CACHE_MISS="miss"
    STATUS_SUCCESS="success"
    STATUS_ERROR="error"
    STATUS_ALL_SKIPPED="all_skipped"
    COULDNT_GENERATE_ANSWER="I'm sorry, I couldn't generate a clear answer."
    COULDNT_REACH_CONCLUSION="I'm sorry, I couldn't reach a conclusion."
    NO_LOCAL_INFO="No relevant information found in local documents."
    NO_INTERNET_INFO="No results found on the internet."
    EMBEDDING_BATCH_FAILED="Failed to embed batch due to persistent errors."

    TG_BOT_ACTIVE_MSG="**RAG Assistant Bot Active**\n\nYou can:\n**Ask a Question**: Just type it here!\n**Upload a Document**: Send a PDF or TXT file."
    TG_NO_ANSWER_FOUND="No answer found."
    TG_FAILED_DOWNLOAD_VOICE="Failed to download voice message."
    TG_STT_KEY_MISSING="STT Error: GROQ_API_KEY not configured in .env"
    TG_TRANSCRIBING_VOICE="Transcribing voice message..."
    TG_NO_CLEAR_SPEECH="Could not transcribe any clear speech."
    TG_SEND_VALID_DOC="Please send a valid document (PDF/TXT)."
    TG_FAILED_DOWNLOAD_FILE="Failed to download file from Telegram."
    TG_INDEXING_DB="Indexing into database..."
